### ISSUE TITLE
Difference between the code and the paper

### ISSUE THREAD

**Issue by Aolius** [shuohangwang/comatch#2]
Thank you for your excellent work, the code is really helpful. The code went well and showed very good results, but I've found the following line different from the equation in the paper. 
They're line 34 and 35 in ./race/comatch.py.
34.  trans_q = self.trans_linear(proj_q)
35.  att_weights = proj_p.bmm( torch.transpose(proj_q, 1, 2) )
It seems that 'trans_q' should replace the 'proj_q' in line 35, according to equation(2) in the paper. But here 'trans_q' is not used anywhere. 
The result is good though, which confused me. Is it because this linear transformation actually doesn't matter a lot?

**Comment by shuohangwang** [comment]
Thank you for the interest in this work! 

And thank you for pointing out the mistake! In my experience, "the linear transformation" won't matter that much, as we already transformed the sentences with LSTM.

Best,
Shuohang
